### ISSUE TITLE
Prerequisites 

### ISSUE THREAD

**Issue by Trashs** [caldav/brand-store-doc#2]
In the sentences below it could be made clearer that the customer needs to provide the email addresses of the store users. i.e. sggest changing this:
...a  list of existing store users (by email) to be defined as uploaders
- A list of existing store users (by email) to be defined as store reviewers
- A list of existing store users (by email) to be defined as store admins

to this:
...a  list of existing store users (specified by their email address) to be defined as uploaders
- A list of existing store users (specified by their email address) to be defined as store reviewers
- A list of existing store users (specified by their email address) to be defined as store admins

**Comment by caldav** [comment]
Fixed by https://github.com/caldav/brand-store-doc/commit/4c8d10be7456a44c090a0f84df1c5a2bc6d08e47

Opened #3 for the cherry-picking tool.
